version: "3.9"
services:
  software:
    build: .
    volumes:
      - ./_source/:/var/www/html
      - ./vhost/:/etc/apache2/conf-available
      - restricted:/var/www/html/_restricted
      - public:/var/www/html/_public
    ports:
      - 658:80
    environment:
      db_host:          "mysql"
      db_user:          "${db_user}"
      db_pass:          "${db_pass}"
      db_name:          "${db_name}"
      db_root_pass:     "${db_root_pass}"
    depends_on:
      - mysql
    profiles:
      - dev
      
  mysql:
    image: mysql
    ports:
      - 23306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE:           "${db_name}"
      MYSQL_ROOT_PASSWORD:      "${db_root_pass}"
      MYSQL_USER:               "${db_user}"
      MYSQL_PASSWORD:           "${db_pass}"
    profiles:
      - dev

volumes:
  mysql:
  restricted:
  public:
